### ISSUE TITLE
ZLJC 离场缺失P9213D

### ISSUE THREAD

**Issue by Liyushen1217** [RudiZhang/VATPRC-official-sector#10]
SID:ZLJC:13:P43203D:JC402 P433 JC403 P432
SID:ZLJC:13:P9203D:JC401 P92
SID:ZLJC:13:P9603D:JC402 P96
SID:ZLJC:31:P43213D:P433 JC403 P432
SID:ZLJC:31:P9613D:JC502 P96

**Comment by RudiZhang** [comment]
@Liyushen1217 完成
