### ISSUE TITLE
部分ATIS CODE被锁定在"A"

### ISSUE THREAD

**Issue by YuchenChien** [RudiZhang/VATPRC-official-sector#11]
**描述BUG**
第三、四栏ATIS（ATIS C & ATIS D）中的ATIS LETTER被锁定在A，无法随ES刷新而刷新；第一、二栏ATIS（ATIS A & ATIS B）工作正常；疑似缺少_atiscode=_

**重现**
打开ES，点击第三/四个ATIS，输入任意机场，**不断**切换菜单中的ATIS LETTER，Test URL。

**截图**
![@SZH~7S11QQ{EYW ~GZWZE1](https://github.com/RudiZhang/VATPRC-official-sector/assets/115696080/1a7f83bc-6120-4c19-ab8d-e27502f8aa0b)

**系统信息**
3.2.3.1 Win11

**Comment by RudiZhang** [comment]
@YuchenChien 已修复
