### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by 7zzzQ** [RudiZhang/VATPRC-official-sector#14]
继上次
GRp场面管制的Approach Window加上跑道号方便识别
GRp自动分配机位做航司适配和机位限制
加一个管制范围区域，方便移交

**Comment by RudiZhang** [comment]
ref #16

**Comment by RudiZhang** [comment]
Approach Window的跑道号，待定
管制范围区域，需要额外配置，待定

**Comment by RudiZhang** [comment]
SOP机场滑行线路 及 场面管制区划分 ref #27

**Comment by RudiZhang** [comment]
下期更新。
