### ISSUE TITLE
ZHHH频率错误

### ISSUE THREAD

**Issue by 7zzzQ** [RudiZhang/VATPRC-official-sector#18]
**描述BUG**
简单清楚的描述BUG
ZHHH频率错误，都是TOWER
**截图**
请提供相关截图或视频
![image](https://github.com/RudiZhang/VATPRC-official-sector/assets/104078922/4a688b51-d68d-4def-8376-975e50a97438)

**Comment by RudiZhang** [comment]
已修复。下期更新
