### ISSUE TITLE
关于指令速度计量单位统一及变更请求

### ISSUE THREAD

**Issue by YuchenChien** [RudiZhang/VATPRC-official-sector#19]
首先 纯公制的速度单位对于新管制员入门不是很友好，甚至针对于已经习惯于英制速度单位的管制员；
其次，topsky ASP给出的速度制是英制，即knots，而当你选中速度时，标牌上的item for assigned speed却是千米时，极度的不协调和不统一，对于实际上线管制影响很大，分散管制员精力；
如果可以的话，强烈建议扇区组在下次更新，更改指令速度单位 统一为英制（节），有需要者自行通过topsky修改回公制（真的有人愿意吗

**Comment by RudiZhang** [comment]
修复，下期更新
