### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by 7zzzQ** [RudiZhang/VATPRC-official-sector#2]
**描述你的功能请求**
用简单易懂的语言描述你想要请求的功能
* GRp场面管制的Approach Window旋转朝向为一致
* GRp场面管制的Approach Window加上跑道号方便识别
* GRp的SOP箭头置下于滑行道标号（滑行线）下
* GRp自动导入机位过于小，导致有些航空器没有停好机位上面会显示不了
* GRp自动分配机位做航司适配和机位限制（如可以）
* 加一个管制范围区域，方便移交
* MTEP RC功能与SOP适配
* 旋转之后的地面扇做一个北向参考标
* 老版本扇区的Profile的配置脚本，省去每次账号密码都又输一遍 

**额外信息**
有关此功能请求的额外信息，例如截图等
![image](https://github.com/RudiZhang/VATPRC-official-sector/assets/104078922/155ecae6-2bff-422a-8239-f3ae565ad04f)
![image](https://github.com/RudiZhang/VATPRC-official-sector/assets/104078922/90831650-fcc9-46ed-91c9-a607e71fab95)

**Comment by RudiZhang** [comment]
[X] Fixed - GRp场面管制的Approach Window旋转朝向为一致
[] Hold - GRp场面管制的Approach Window加上跑道号方便识别 **需手动配置，单独另开issue**
[X] Fixed - GRp的SOP箭头置下于滑行道标号（滑行线）下
[X] Fixed - GRp自动导入机位过于小，导致有些航空器没有停好机位上面会显示不了
[] Hold - GRp自动分配机位做航司适配和机位限制（如可以） **单独另开issue**
[] 加一个管制范围区域，方便移交
[] MTEP RC功能与SOP适配
[X] Fixed - 旋转之后的地面扇做一个北向参考标 **Approach Windows中会自动出现**
[X] No Fix - 老版本扇区的Profile的配置脚本，省去每次账号密码都又输一遍 **压缩包中有**

**Comment by RudiZhang** [comment]
@7zzzQ Hold的内容，请重新开新的issue。
