### ISSUE TITLE
呼和浩特地面扇缺少J等待点；部分导航台数据缺失导致STAR显示问题；CPDLC/DCL的Logon取消自动模式

### ISSUE THREAD

**Issue by YuchenChien** [RudiZhang/VATPRC-official-sector#24]
**呼和浩特地面扇缺少J等待点**
![image](https://github.com/RudiZhang/VATPRC-official-sector/assets/115696080/05d43f3e-7bcf-4981-a391-f1fead9bf2b8)
![image](https://github.com/RudiZhang/VATPRC-official-sector/assets/115696080/d1173dd0-7dbc-4ee1-afd5-07587054c8b8)

**部分导航台数据缺失导致STAR显示问题**
![R1W9FWJ8II2)QXV~J MG5}P](https://github.com/RudiZhang/VATPRC-official-sector/assets/115696080/84672f94-aee3-467b-8e32-c7ee64ad0c68)
![~ Y14{C64S3E@5H)ZQ6LB1](https://github.com/RudiZhang/VATPRC-official-sector/assets/115696080/7b83e82f-ea01-40de-a4b3-8d2fb9b248f0)

**CPDLC/DCL auto**
略图

**Comment by RudiZhang** [comment]
完成。下期更新
