### ISSUE TITLE
ES ATIS问题

### ISSUE THREAD

**Issue by CSN9022** [RudiZhang/VATPRC-official-sector#25]
**描述BUG**
登录进离场混合ATIS时 自动生成为离场ATIS 无进场跑道信息

**重现**
登录ATIS即可

**截图**
请提供相关截图或视频
![QQ截图20240322140829](https://github.com/RudiZhang/VATPRC-official-sector/assets/117365522/79c6de93-87cf-4c34-a9e6-cee363d9a03b)

**系统信息**
 - ES版本 3.2.9
 - Windows版本 Windows11 23H2
 - 或其他相关

**额外信息**
有关此问题的额外信息

**Comment by RudiZhang** [comment]
非BUG，请查看Moodle。
