### ISSUE TITLE
Fixes 缺失

### ISSUE THREAD

**Issue by YetTao** [RudiZhang/VATPRC-official-sector#26]
在每一个FIR扇区里面，无法寻找到与飞机截获盲降的定位点等等的FIXES

如：在北京（ZBAA）CI19Z（40.310419444,116.577944444）、FI19Z(40.181269444,116.598375000)等一系列点的位置

**Comment by RudiZhang** [comment]
原始数据库资料中不包括该类数据，故没有加入到扇区中的打算

**Comment by AaronZSAM101** [comment]
@YetTao 怎么了？没有CI19Z FI19Z影响你OBS吗？还是影响你帮助他人出技术？
