### ISSUE TITLE
ZJSY 地面扇区 A8滑行道勘误

### ISSUE THREAD

**Issue by YuchenChien** [RudiZhang/VATPRC-official-sector#28]
ZJSY B8南侧的A8滑行道目测不存在 应由B8联通至A 附图
![IMG_9184](https://github.com/RudiZhang/VATPRC-official-sector/assets/115696080/bc072b17-b742-4a14-872a-0e5185eeb5a7)
![IMG_9185](https://github.com/RudiZhang/VATPRC-official-sector/assets/115696080/fbde6321-7c80-4f9a-8230-8c3f597de63b)

**Comment by haochenshen** [comment]
已修改

**Comment by RudiZhang** [comment]
下期更新
