### ISSUE TITLE
SID 程序

### ISSUE THREAD

**Issue by YetTao** [RudiZhang/VATPRC-official-sector#31]
1. ZSPD-ZBAA的航路如下：POMOK G330 PIMOL A593 DALIM W157 AVBOX
如果按照传统选PIK81D、82D、86D等程序的话，会先走完SID再走到POMOK再回去PIKAS，可以把SID做成如STAR类似的，比如：PIK81DxPOMOK或者其他样式

2.是否可以让扇区和以前的CAB扇一样，机场扇区可以分出Ground Radar和Topsky扇区

**Comment by RudiZhang** [comment]
1. 导致的原因为ES的逻辑问题，有计划但短期内应该不会修复
2. 不在考虑范畴，请尽快熟悉Ground Radar

**Comment by AaronZSAM101** [comment]
@YetTao 呀 为什么要分开呢？是分开了就不会管制了吗？还是分开了不方便二次修改编译他人的劳动成果而后获利？

**Comment by YanakiSako** [comment]
@YetTao 呀 为什么要分开呢？是分开了就不会管制了吗？还是分开了不方便二次修改编译他人的劳动成果而后获利？
