### ISSUE TITLE
允许用户整体更改标牌菜单大小

### ISSUE THREAD

**Issue by bruceyang1998** [RudiZhang/VATPRC-official-sector#33]
**描述你的功能请求**
VATSIM管制员使用的硬件不尽相同，用4K显示器的管制员需要更大字号，1080p显示器的管制员需要更小字号，希望能有设置工具能整体更改所有ES/TopSky文字大小

**额外信息**
- VATSIM CID 1259390

**Comment by RudiZhang** [comment]
修复。下期更新。

**Comment by 7zzzQ** [comment]
终于有人提出来了
