### ISSUE TITLE
STAR

### ISSUE THREAD

**Issue by ghost** [RudiZhang/VATPRC-official-sector#34]
ZBAA-18R/18L/19-GUV8YA程序无法找到

![image](https://github.com/RudiZhang/VATPRC-official-sector/assets/143585060/b4bb2941-2b9f-4433-93ea-ac206abafe00)

**Comment by RudiZhang** [comment]
@YetTao 请提供VATSIM CID

**Comment by YetTao** [comment]
VATSIM CID：1669083

**Comment by AaronZSAM101** [comment]
@YetTao 
找不找得到 这个不知道呢 这边建议你自己先修一下 不然你要出不了别人的技术帮助别人了

**Comment by YanakiSako** [comment]
@YetTao

**Comment by RudiZhang** [comment]
修复。下期更新。
