### ISSUE TITLE
给部分二创他人扇区的人看的

### ISSUE THREAD

**Issue by AaronZSAM101** [RudiZhang/VATPRC-official-sector#35]
**描述你的功能请求**
敬告：某些未经许可二次创作、编译、发布、售卖扇区等相关资料的人趁早收手。
**Ctrl+C Ctrl+V一下别人的劳动成果，Ctrl+H替换一下别人的版权说明为自己的就是自己做的了？？**

**Comment by RudiZhang** [comment]
# VATPRC Topsky 标准扇区使用协议：
- 唯一发布网址 -> https://www.vatprc.net/sector

- 扇区著作权归VATSIM中华人民共和国分部所有

- **仅限VATSIM平台使用**

- **禁止在未经书面授权的情况下二次开发、编译、发布、售卖等**

- 扇区中所有内容与现实无关，请勿用于现实

- 充分理解并尊重著作权

- 下载扇区即同意上述协议。VATPRC保留处理违反上述协议成员的权力。VATPRC保留上述使用协议的最终解释权。

**Comment by RudiZhang** [comment]
取消公开
