### ISSUE TITLE
建议修改Topsky默认CFL的配置

### ISSUE THREAD

**Issue by mic12130** [RudiZhang/VATPRC-official-sector#36]
**描述BUG**
目前Topsky默认CFL设置为auto，可能导致打开CFL menu时不默认高亮CFL而是RFL，进近管制遇到这种情况会不太方便

**重现**
打开任意飞机的CFL menu

**截图**
<img width="203" alt="image" src="https://github.com/RudiZhang/VATPRC-official-sector/assets/26357139/e96443c8-b780-4ec2-98b5-71e6c6362bd8">

此时飞机CFL是1500，CFL menu默认高亮RFL 1040

**系统信息**
 - ES 3.2.9
 - Windows 11
- 1297819

**额外信息**
建议将该设置从auto改为cfl
在TopSkySettings.txt中加一行```Label_CFL_DefaultValue=1```即可

**Comment by RudiZhang** [comment]
修复。下期更新
