### ISSUE TITLE
ZHCC

### ISSUE THREAD

**Issue by ghost** [RudiZhang/VATPRC-official-sector#37]
![image](https://github.com/RudiZhang/VATPRC-official-sector/assets/165481603/51183371-4319-45d6-9ecc-1ae59d9de614)
![image](https://github.com/RudiZhang/VATPRC-official-sector/assets/165481603/14f316fc-fba8-4030-8f0b-6db6a6908fbb)
如图，滑行道D1没有

VATSIM CID：1753867

**Comment by RudiZhang** [comment]
@haochenshen

**Comment by RudiZhang** [comment]
修复。下期更新
