### ISSUE TITLE
List

### ISSUE THREAD

**Issue by ghost** [RudiZhang/VATPRC-official-sector#38]
如果一个机组先在一个机场落地的话，然后他的STS自动被分配为了ARR，此时如果这个机组继续提交了一个起飞机场为这个机场的飞行计划，默认全部List中都不会出现这个机组的信息，但是Departure List将不会有这个bug无论STS为如何。

**Comment by RudiZhang** [comment]
@Hongsuo1 请提供VATSIM CID

**Comment by ghost** [comment]
VATSIM CID：1753867

**Comment by RudiZhang** [comment]
这个原因是VATSIM FSD导致的，请联系VATSIM技术团队。另外，你似乎并不是VATSIM的管制员，请遵守扇区使用协议。

**Comment by YuchenChien** [comment]
这位同志好像给不了放行呀:)
为什么会用到list呢
