### ISSUE TITLE
TopskyMap

### ISSUE THREAD

**Issue by ghost** [RudiZhang/VATPRC-official-sector#40]
如下图所示，激活的对应机场的跑道显示出的STAR路线上的点的名称会与白色的移交高度冲突
![image](https://github.com/RudiZhang/VATPRC-official-sector/assets/165481603/b7cdd220-c9fd-47d1-a902-4967675b0891)

VATSIM CID：1753867

**Comment by RudiZhang** [comment]
后续会以其他形式呈现，暂不修复。
