### ISSUE TITLE
北京地面扇区跑道18L的W8联络道与航图不一致

### ISSUE THREAD

**Issue by DapengLiu01** [RudiZhang/VATPRC-official-sector#41]
最新航图上跑道18L的W8联络道已经不使用，2404扇区内的W8联络道依然存在。
![ac845a6086f1b78a6d09e259c67a7431](https://github.com/RudiZhang/VATPRC-official-sector/assets/105977262/f64f67db-6fbd-4e6f-ba44-de0757a71ca7)
![f06e38fc4a9d244b9c154a893cd90733](https://github.com/RudiZhang/VATPRC-official-sector/assets/105977262/3bd54386-7c67-4a49-a84a-156360f7d46f)

**Comment by YuchenChien** [comment]
![image](https://github.com/RudiZhang/VATPRC-official-sector/assets/115696080/96838770-8901-495b-9c7e-9e77d2df018c)
W8 D9 目前均不再使用

**Comment by YuchenChien** [comment]
![image](https://github.com/RudiZhang/VATPRC-official-sector/assets/115696080/d6500497-76db-41ac-8ac9-a5d220bf72a6)
![image](https://github.com/RudiZhang/VATPRC-official-sector/assets/115696080/c5640299-5950-46a4-9b50-1f7c4cab49a5)
W1目前不可用

**Comment by YuchenChien** [comment]
缺少C8标记 缺少未标注的滑行道
![image](https://github.com/RudiZhang/VATPRC-official-sector/assets/115696080/6e71c00b-dc50-4d30-9d1a-82b8e13279d9)
![image](https://github.com/RudiZhang/VATPRC-official-sector/assets/115696080/0b6f6637-f9b6-468a-a70b-4cc28ade9ac4)

**Comment by XuanyanYe** [comment]
已通知 @haochenshen
