### ISSUE TITLE
广州SOP滑行路线完善

### ISSUE THREAD

**Issue by FSA1519** [RudiZhang/VATPRC-official-sector#42]
如图所示：
![72D60D187D2754FC2D703571A5C48D0F](https://github.com/RudiZhang/VATPRC-official-sector/assets/162720319/5bffab56-8277-48b2-a603-5f0c9d4c2941)
![5AC2C932B12CB550EEB0106102C35D18](https://github.com/RudiZhang/VATPRC-official-sector/assets/162720319/0a4fdcec-cc98-4691-b2b7-5105f10b2308)

CID: 1435638

**Comment by RudiZhang** [comment]
@FSA1519 修复，下期更新。
