### ISSUE TITLE
ZBSJ MVA

### ISSUE THREAD

**Issue by ghost** [RudiZhang/VATPRC-official-sector#44]
![image](https://github.com/RudiZhang/VATPRC-official-sector/assets/165481603/a9422342-82d4-4526-8e09-70b3afa7c865)
AIP 航图中最新2404的ZBSJ MVA如上图，与扇区内mva内容不符
![image](https://github.com/RudiZhang/VATPRC-official-sector/assets/165481603/cb3de80d-cbf3-4716-845e-e3b4f93863b3)

**Comment by ghost** [comment]
VATSIM CID：1753867

**Comment by ghost** [comment]
![image](https://github.com/RudiZhang/VATPRC-official-sector/assets/165481603/f3e5dcb5-f715-4a3a-a087-7b6561b54134)
ZGHA也不符和AIP
![image](https://github.com/RudiZhang/VATPRC-official-sector/assets/165481603/8060718a-0eb7-4ff2-8616-4f64608accdd)

**Comment by RudiZhang** [comment]
修复。下期更新。
