### ISSUE TITLE
ZGGG地面

### ISSUE THREAD

**Issue by ghost** [RudiZhang/VATPRC-official-sector#45]
![image](https://github.com/RudiZhang/VATPRC-official-sector/assets/165481603/51f2d0e9-21c9-4127-ace9-8ac37b40ba1a)
![image](https://github.com/RudiZhang/VATPRC-official-sector/assets/165481603/ddbbf1b0-6fa6-489c-a681-ffeccf37aaf2)
地面滑行方向建议加入

**Comment by ghost** [comment]
VATSIM CID：1753867

**Comment by XuanyanYe** [comment]
滑行方向目前仅对SOP已规定机场进行配置

**Comment by ghost** [comment]
![image](https://github.com/RudiZhang/VATPRC-official-sector/assets/165481603/c27ae355-e372-40ef-8c59-0e6d7bbe1c2f)
ZGGG不属SOP机场？

**Comment by XuanyanYe** [comment]
需要SOP对此有规定滑行方向才会划设箭头，如无则不进行箭头标注

**Comment by ghost** [comment]
![image](https://github.com/RudiZhang/VATPRC-official-sector/assets/165481603/08bba2a4-528c-4f3e-8f22-bb4b5a4d513d)
这不算规定？

**Comment by RudiZhang** [comment]
ref #42

**Comment by YuchenChien** [comment]
你好，
我对于你在 https://github.com/KingfuChan/MTEPlugin-for-EuroScope/issues/11 中的对话，提出若干温馨提醒：
1. MTEP中航路检查项的拼写是RouteChecker，而不是RouteCheak；
2. 鉴于你在本板块对VATPRC官方扇区建言献策或是提出疑点，我推测你在使用VATPRC官方扇区。你在 https://github.com/KingfuChan/MTEPlugin-for-EuroScope/issues/11 中擅自修改RouteChecker的.csv内容，以上行为与 https://www.vatprc.net/sector 中描述的协议相悖；
3. 我对你在本版块留下的CID，在VATSIM官方统计系统中进行了查询动作。CID1753867在VATSIM网络中并没有连线作为管制观察员的身份，参考 https://stats.vatsim.net/stats/1753867 ；
4. 我对于你在 https://github.com/KingfuChan/MTEPlugin-for-EuroScope/issues/11 中记录下的CBJ1672，进行了同第三点的查询。据结果，CBJ1672并未在VATSIM网络中出现。参考 https://stats.vatsim.net/search/CBJ1672 ；
5. 结果显示，你并未在VATSIM网络中使用扇区，相关机组呼号也并未是VATSIM网络中出现过的机组呼号。

请您严格遵守 https://www.vatprc.net/sector 中标注的**VATPRC Topsky 标准扇区使用协议**。

敬告，
Yuchen Qian   1489005

**Comment by AaronZSAM101** [comment]
> ![image](https://github.com/RudiZhang/VATPRC-official-sector/assets/165481603/08bba2a4-528c-4f3e-8f22-bb4b5a4d513d)
> 
> 这不算规定？

您好，我是ZGGG场面SOP主要作者之一。不知是否是表达不清晰还是如何，原文意思是：该部分可在相关航图查看。请您参阅相关航图，感谢。

对于未及时更新的航图编号，SOP编写组已纳入工作计划。感谢您的提出。

另外，您非VATPRC或其他分部管制员，请您遵守扇区使用协定。感谢您的配合。

Mengqiu / 1478665

**Comment by Yuziki1227** [comment]
您好，
我是VATPRC扇区开发组成员之一，据我目前可掌握的消息，您并非VATPRC或是VATSIM的管制员，看您对VATPRC扇区提交了很多Issue，首先感谢您对VATPRC扇区开发的支持，其次，我有几点疑问想询问您：
1.在VATPRC扇区不公开的时候（约2401/02周期），您便已经拿到了VATPRC扇区，在当时一位VATPRC管制员询问您的时候，您自己声称扇区是"取色器"照抄的调色，并展示了VATPRC分部管制员登录ZHHH_TWR的截图，声称是根据该截图进行取色调色的扇区，但我想问您真的用的到VATCAN Booking这个插件么？
2.在VATPRC扇区公开以后，您多次提交Issue,但您并非分部管制员,我们询问了您扇区用途，您表示是OBS VATSIM管制员使用的，我们便没有过多追问.

但近期，有人向我举报您在"空中云端"(官网:hkyfly.com)使用了VATPRC分部扇区，但举报人并没有提供有效的证据能证明使用扇区的7517是您本人，但作为开发者，我还是想提醒您请遵守 VATPRC Topsky 标准扇区使用协议 ，
敬重！

Mingchun Chen / 1737036
