### ISSUE TITLE
过站机组可能不显示在Startup List

### ISSUE THREAD

**Issue by 1917604180** [RudiZhang/VATPRC-official-sector#48]
**描述BUG**
过站不断线且不更改呼号，仅重新提交计划可能会导致机组不会出现在startup list

**截图**
![QQ截图20240615235135](https://github.com/RudiZhang/VATPRC-official-sector/assets/61542874/93c85267-5e89-48aa-bf70-a3512bce773f)
图中CCA461到达后提交前往ZBAA的计划，但并未出现在startup list中，无法通过list修改标牌

**系统信息**
 - ES版本 3.2.9
 - Windows版本 Windows10 22H2
- VATSIM CID 1433359
- 扇区版本 2405

**额外信息**
有关此问题的额外信息

**Comment by XuanyanYe** [comment]
这个问题是ES逻辑造成的，与扇区自身无关
