### ISSUE TITLE
ZBER 二连浩特地面扇更新

### ISSUE THREAD

**Issue by JingyuanYin** [RudiZhang/VATPRC-official-sector#49]
**描述你的功能请求**
ZBER 二连浩特地面扇更新

**额外信息**
- VATSIM CID 1478847
- 有关此功能请求的额外信息，例如截图等
![屏幕截图 2024-06-21 224243](https://github.com/RudiZhang/VATPRC-official-sector/assets/67865939/26c541c0-d239-48c1-a11a-86b3f8f91306)
![QQ图片20240621224620](https://github.com/RudiZhang/VATPRC-official-sector/assets/67865939/5a0a8fef-1953-40c6-8a0c-b3d037c76d26)

**Comment by XuanyanYe** [comment]
Ref #50
