### ISSUE TITLE
ZJSY 三亚/凤凰 进场程序问题

### ISSUE THREAD

**Issue by YuchenChien** [RudiZhang/VATPRC-official-sector#7]
ZJSY 三亚/凤凰 进场程序问题
ES 3.2.3.1 Win11

UPR8YA/08 中出现本不应该在该程序中的点 SY801

附图
![YMWAVK4XPQ1SIH{41K`~O$O](https://github.com/RudiZhang/VATPRC-official-sector/assets/115696080/07b83e46-70bc-4ca0-bf57-2e9e9493e79b)
![6)7NFO)6MJFPGCSB8WYR%3H](https://github.com/RudiZhang/VATPRC-official-sector/assets/115696080/7a2b9d1d-e026-4e18-823e-d03cad027677)
![IXV)GQ29N@~QVIY%_7S$VBJ](https://github.com/RudiZhang/VATPRC-official-sector/assets/115696080/811ded2a-e421-492b-8a46-eeab7b64117d)

**Comment by RudiZhang** [comment]
@YuchenChien 经核实 SY801在该程序中 
![image](https://github.com/RudiZhang/VATPRC-official-sector/assets/40914896/eb082d3b-7952-4173-992b-13af27c2e171)

回炉吧你
