### ISSUE TITLE
VOR Symbols

### ISSUE THREAD

**Issue by AaronZSAM101** [RudiZhang/VATPRC-official-sector#8]
**描述BUG**
有人数学不好我不说是谁，建议重修初中平面直角坐标系

**重现**
肉眼观察

**截图**
- 修复前
![image](https://github.com/RudiZhang/VATPRC-official-sector/assets/60245950/ff15aca0-2908-46c5-849b-789090898a65)
- 修复后
![image](https://github.com/RudiZhang/VATPRC-official-sector/assets/60245950/18a194c0-c189-4b46-be74-229af4ccc083)

**系统信息**
 - ES版本：
 - Windows版本：
 - 或其他相关：

**额外信息**
```
MOVETO:-7:0
LINETO:-3:6
LINETO:3:6
LINETO:7:0
LINETO:3:-6
LINETO:-3:-6
LINETO:-7:0
LINETO:-7:6
LINETO:7:6
LINETO:7:-6
LINETO:-7:-6
LINETO:-7:0
POLYGON:-1:1:1:1:1:-1:-1:-1
```

**Comment by RudiZhang** [comment]
@AaronZSAM101 完成。
